version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: puzzlestore_db
    restart: always
    environment:
      POSTGRES_DB: puzzlestore_db
      POSTGRES_USER: puzzlestore_user
      POSTGRES_PASSWORD: puzzlestore_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: