# Generated by Django 6.0.4 on 2026-04-23 19:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название ограничения')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Минимальный возраст')),
            ],
            options={
                'verbose_name': 'Возрастное ограничение',
                'verbose_name_plural': 'Возрастные ограничения',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя создателя')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Роль (дизайнер/художник и т.д.)')),
            ],
            options={
                'verbose_name': 'Создатель',
                'verbose_name_plural': 'Создатели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название издателя')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Издатель',
                'verbose_name_plural': 'Издатели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название игры')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-слаг')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Текущий остаток на складе')),
                ('rating_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Средний рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('age_limit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_games', to='puzzlestore.agelimit', verbose_name='Возрастное ограничение')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_games', to='puzzlestore.publisher', verbose_name='Издатель')),
            ],
            options={
                'verbose_name': 'Настольная игра',
                'verbose_name_plural': 'Настольные игры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Себестоимость за единицу')),
                ('supply_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата поставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='puzzlestore.boardgame', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'ordering': ['-supply_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Хэш пароля')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на аватар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='puzzlestore.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи за единицу')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата продажи')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='puzzlestore.boardgame', verbose_name='Игра')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='puzzlestore.user', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='BoardGameCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creators', to='puzzlestore.boardgame', verbose_name='Игра')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='puzzlestore.creator', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Создатель игры',
                'verbose_name_plural': 'Создатели игр',
                'ordering': ['game', 'creator'],
                'unique_together': {('game', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='BoardGameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='puzzlestore.boardgame', verbose_name='Игра')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='puzzlestore.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр игры',
                'verbose_name_plural': 'Жанры игр',
                'ordering': ['game', 'genre'],
                'unique_together': {('game', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_carts', to='puzzlestore.boardgame', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='puzzlestore.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Корзины',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Желаемое количество')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_wishlists', to='puzzlestore.boardgame', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='puzzlestore.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Товар в желаемом',
                'verbose_name_plural': 'Желаемое',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
