# Generated by Django 6.0.4 on 2026-04-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlestore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='country',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='website',
        ),
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='note',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='creator',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Роль в создании (дизайнер/художник и т.д.)'),
        ),
    ]
