# Generated by Django 6.0.4 on 2026-04-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlestore', '0002_remove_boardgame_slug_remove_genre_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='genres',
            field=models.ManyToManyField(related_name='board_games', to='puzzlestore.genre', verbose_name='Жанры'),
        ),
        migrations.DeleteModel(
            name='BoardGameGenre',
        ),
    ]
