# Generated by Django 6.0.4 on 2026-06-04 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlestore', '0006_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='creators',
            field=models.ManyToManyField(related_name='board_games', through='puzzlestore.BoardGameCreator', through_fields=('game', 'creator'), to='puzzlestore.creator', verbose_name='Создатели'),
        ),
        migrations.AlterField(
            model_name='boardgamecreator',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_links', to='puzzlestore.creator', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='boardgamecreator',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_links', to='puzzlestore.boardgame', verbose_name='Игра'),
        ),
    ]
