# Generated by Django 6.0.4 on 2026-06-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlestore', '0007_boardgame_creators_alter_boardgamecreator_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='rules_file',
            field=models.FileField(blank=True, null=True, upload_to='rules/%Y/%m/%d/', verbose_name='Правила (PDF)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
