# Generated by Django 6.0.4 on 2026-06-04 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlestore', '0008_remove_boardgame_image_url_remove_profile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт издателя'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='rules_file',
            field=models.FileField(blank=True, null=True, upload_to='rules/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Файл правил должен быть в формате PDF')], verbose_name='Правила (PDF)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
