# Generated by Django 6.0.4 on 2026-06-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlestore', '0009_publisher_website_alter_boardgame_image_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='boardgame',
            constraint=models.UniqueConstraint(fields=('name', 'publisher'), name='unique_game_publisher'),
        ),
    ]
